# numpy fumctions

In [1]:
import numpy as np

# arange function

# np.arange(startvalye,stop value,steps)

In [2]:
array_1d=np.arange(1,13)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
arr1d=np.arange(1,31)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
arr_even=np.arange(2,30,2)
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
array_odd_1d=np.arange(1,30,2)
print(array_odd_1d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


# linspace()

In [6]:
arr_1d=np.linspace(1,6,5)
print(arr_1d)

[1.   2.25 3.5  4.75 6.  ]


# resahpe()

In [7]:
#convertng 1d array to 3d array

In [8]:
array_1d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arr1d.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr1d.reshape(5,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]])

In [11]:
#1d array to 3d array

In [12]:
array_1d.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
array_1d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# arange and reshape work togather


In [14]:
arr_ml=np.arange(1,31).reshape(5,3,2)
arr_ml

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]])

In [15]:
array_1d.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
array_2dd=np.arange(1,13).reshape(6,2)
print(array_2dd)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [17]:
array_2dd=np.arange(1,13).reshape(4,3)
print(array_2dd)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#first array convert ki arange ki help se 1 to 12 tak n than reshape se 1d arrey ko 2d array me conert kar diya

# ravel function =it convert multidimentional array to 1 d array

In [19]:
arr_ml.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
array_2dd.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose() =this function convert column into row

In [21]:
arry_t=np.arange(1,31).reshape(10,3)
arry_t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [22]:
arry_t.transpose()

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [23]:
arr=np.arange(1,13).reshape(6,2)
arr


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
arr.transpose()

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [27]:
arr[:5]=500
arr

array([[500, 500],
       [500, 500],
       [500, 500],
       [500, 500],
       [500, 500],
       [ 11,  12]])