In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
#function for ones matrix

In [7]:
mx_1s=np.ones(4)
print(mx_1s)

[1. 1. 1. 1.]


mx_1s.dtype

In [8]:
mx_1s.dtype

dtype('float64')

In [9]:
mx_1s=np.ones((3,3))
print(mx_1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
mx_0s=np.zeros((5,6),dtype=int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [15]:
mx_0s=np.zeros((5,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [16]:
mx_1s=np.ones((3,4),dtype=bool)
print(mx_1s)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [17]:
mx_1s=np.ones((3,4),dtype=str)
print(mx_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [18]:
mx_0s=np.zeros((5,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [19]:
#this is our empty string,0=flase,1=true 


In [21]:
em_str=''
print(bool(em_str))

False


In [22]:
em_str='1'
print(bool(em_str))

True


In [24]:
mx_em=np.empty((4,4))
print(mx_em)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33646845e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 7.56605918e-307 5.33590898e-322]]
