# mathematic operation using Numpy

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
ar1=np.arange(1,17).reshape(4,4)
ar2=np.arange(17,33).reshape(4,4)
print(ar1)
ar2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [43]:
ar1+ar2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [3]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
#add function

In [5]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [44]:
np.add(ar1,ar2)

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [48]:
np.subtract(ar2,ar1)

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [45]:
np.subtract(ar1,ar2)

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [6]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
#subtract function
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
np.divide(ar1,ar2)

array([[0.05882353, 0.11111111, 0.15789474, 0.2       ],
       [0.23809524, 0.27272727, 0.30434783, 0.33333333],
       [0.36      , 0.38461538, 0.40740741, 0.42857143],
       [0.44827586, 0.46666667, 0.48387097, 0.5       ]])

In [50]:
np.multiply(ar1,ar2)

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [8]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#devide function

In [10]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
#multiflication function

In [13]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# matrix wise solution


# 

In [51]:
ar1@ar2

array([[ 250,  260,  270,  280],
       [ 618,  644,  670,  696],
       [ 986, 1028, 1070, 1112],
       [1354, 1412, 1470, 1528]])

In [14]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
#array solving matrix wise for function

In [53]:
ar1.dot(ar2)

array([[ 250,  260,  270,  280],
       [ 618,  644,  670,  696],
       [ 986, 1028, 1070, 1112],
       [1354, 1412, 1470, 1528]])

In [16]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [17]:
#array metrix me agar max value dhundna ho to

In [18]:
arr1.max()

9

In [55]:
ar1.max()

16

In [19]:
#if hme max value ka index janna ho

In [56]:
ar1.argmax()

15

In [20]:
arr1.argmax()

8

In [21]:
#agar hme perticler row ya colem max pta karna ho to
#0=row
#1=colem

In [57]:
ar1.max(axis=1)

array([ 4,  8, 12, 16])

In [58]:
ar1.max(axis=0)

array([13, 14, 15, 16])

In [22]:
arr1.max(axis=0)

array([7, 8, 9])

In [23]:
arr1.max(1)

array([3, 6, 9])

In [24]:
arr1.min()

1

In [25]:
arr1.min(1)

array([1, 4, 7])

In [26]:
arr1.min(axis=0)

array([1, 2, 3])

In [27]:
arr1.argmin()

0

In [ ]:
#if we want so sum a array

In [28]:
np.sum(arr1)

45

In [59]:
np.sum(ar1)

136

In [60]:
np.sum(ar2)

392

In [61]:
#agar kisi row ya column ka sum janan ho to

In [62]:
np.sum(ar1,axis=0)

array([28, 32, 36, 40])

In [63]:
#column vise sum janna ho to
np.sum(ar1,axis=1)

array([10, 26, 42, 58])

In [29]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [30]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [31]:
#mean fuction = agar hme puri array ka mean janna ho to
np.mean(arr1)

5.0

In [64]:
np.mean(ar1)

8.5

In [67]:
np.median(ar1)

8.5

In [32]:
#scareroot functio
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [33]:
#standard devision fo function
np.std(arr1)

2.581988897471611

In [34]:
#exponent function

In [35]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [36]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
#log 10 function
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])