In [1]:

import numpy as np

In [2]:
array_1d=np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [3]:
type(array_1d)

numpy.ndarray

In [4]:
array_1d.ndim

1

In [5]:
array_2d=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(array_2d)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [15]:
arr2d=np.array([[4,5,6],[7,8,9],[10,11,12]])
arr2d

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
arr2d.ndim
arr2d.size
arr2d.shape
arr2d.dtype

dtype('int32')

In [6]:
type(array_2d)

numpy.ndarray

In [7]:
array_2d.ndim

2

In [8]:
array_2d.size

15

In [9]:
array_1d.size

4

In [10]:
array_2d.shape

(3, 5)

In [11]:
#here 3 is row and 5 is colem

In [12]:
array_2d.dtype

dtype('int32')

In [13]:
array_2d.size

15

In [14]:
print(array_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
