In [1]:
import numpy as np

mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

In [2]:
import numpy as np

# ones matrix


In [14]:
ones_mx=np.ones((5))
ones_mx

array([1., 1., 1., 1., 1.])

In [23]:
#if we want int value in our array than
mx_1=np.ones((5,5),dtype=int)
print(mx_1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# zero metrix

In [22]:
zero_mx=np.zeros((4,5),dtype=int)
zero_mx

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])