# python Numpy Tutorial-8

# Random sampling with Numpy

In [1]:
#for genarating random data we using random module


In [2]:
import numpy as np

In [3]:
import random

In [5]:
np.random.random(1)

array([0.27739105])

#2d array by using random function

In [7]:
np.random.random((3,3))

array([[0.32653796, 0.22079572, 0.63919708],
       [0.52262266, 0.4121701 , 0.76096756],
       [0.02053328, 0.0842691 , 0.15963134]])

In [11]:
#if we want int value
np.random.randint(1,4)

3

In [12]:
#if we want random int matrix

In [15]:
np.random.randint(1,4,(4,4))

array([[2, 3, 1, 3],
       [3, 2, 1, 1],
       [2, 2, 1, 1],
       [3, 2, 2, 1]])

In [18]:
np.random.randint(1,4,(2,4,4))

array([[[3, 2, 2, 3],
        [1, 3, 3, 2],
        [2, 1, 1, 3],
        [3, 1, 2, 3]],

       [[2, 3, 3, 1],
        [2, 3, 3, 2],
        [1, 3, 1, 3],
        [1, 1, 1, 3]]])

In [22]:
#if next time we want  same random generated value, for we using np.random.seed(value) function
#after using this function we can use same generated value when we want 

In [20]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))


array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [23]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [24]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [25]:
#hmesa same random value genrate hongi seed function ke use karne se

In [26]:
#np.random.rand((shape))= ye function se ham nd array create kar sakte hai
np.random.rand((3))

array([0.13145815, 0.41366737, 0.77872881])

In [29]:
np.random.rand(3,3)
#is function se only 0 se 1ke bich ki value milti hai

array([[0.61194334, 0.33188226, 0.55964837],
       [0.33549965, 0.41118255, 0.0768555 ],
       [0.85304299, 0.43998746, 0.12195415]])

In [30]:
#np.random.randn(shape)=negative and positiv value deta hai between o to 1
np.random.randn(3,3)

array([[-0.6579709 ,  0.42211306,  0.62402334],
       [ 0.5016401 ,  0.84143473, -1.64024998],
       [ 1.05800516, -0.09178444, -0.72403459]])

In [34]:
x=[1,2,3,4,5]
#agar hme koi random single value chahiye list me se
#np.random.choice(x)
#koi bhi list ki single value mil jayegi
np.random.choice(x)

5

In [38]:
for i in range(30):
    f=np.random.choice(x)
    print(f)

2
3
2
3
2
4
3
4
5
5
1
3
3
1
1
3
1
3
3
1
5
2
4
3
4
4
1
5
2
3


In [39]:
#prmutation function=ye function hmari list ko prut karke de deta hai
#np.random.permutation(list_variable)
np.random.permutation(x)

array([2, 3, 4, 5, 1])

In [40]:
np.random.permutation(x)

array([1, 2, 4, 3, 5])

In [41]:
for i in range(30):
    f=np.random.permutation(x)
    print(f)

[2 3 4 1 5]
[4 3 1 2 5]
[1 2 3 5 4]
[1 3 5 4 2]
[1 5 2 4 3]
[4 2 3 5 1]
[3 2 5 4 1]
[3 1 4 5 2]
[5 3 2 1 4]
[4 1 2 3 5]
[2 5 4 3 1]
[1 3 5 2 4]
[3 2 5 4 1]
[1 5 4 3 2]
[3 1 4 5 2]
[2 4 3 1 5]
[4 2 5 3 1]
[4 1 3 2 5]
[4 2 3 5 1]
[3 2 1 5 4]
[5 3 4 1 2]
[1 5 3 4 2]
[1 4 2 5 3]
[5 2 1 4 3]
[3 4 5 1 2]
[5 4 1 3 2]
[2 4 1 5 3]
[3 4 5 2 1]
[5 3 4 2 1]
[1 2 3 5 4]
