# python numpy conctination and split

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2=np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
#if hme list cocatinate karna ho to
l=[1,2,3,4,5]
l2=[7,8,9,4,5]

In [5]:
l+l2

[1, 2, 3, 4, 5, 7, 8, 9, 4, 5]

In [6]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [7]:
#if hme array concatinate karna ho to

In [8]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [9]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [10]:
np.vstack((arr1,arr2))#column wise concatenate karta hai

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [11]:
np.hstack((arr1,arr2))#row wise concatenate karta hai

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# split functions

In [12]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [13]:
np.split(arr1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [14]:
l=np.split(arr1,2)

In [17]:
type(l)

list

In [18]:
l[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
type(l[0])

numpy.ndarray

In [20]:
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

1dar=np.array([1,2,3,4,5])
np.split(1dar,[2,4])

In [21]:
dar=np.array([1,2,3,4,5])
np.split(dar,[2,4])

[array([1, 2]), array([3, 4]), array([5])]

In [22]:
dar=np.array([1,2,3,4,5])
np.split(dar,[1,4])

[array([1]), array([2, 3, 4]), array([5])]